---
abstract: 'A parser for the IRC protocol.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-IRC
requires:
  perl: 5.006
resources:
  homepage: https://github.com/bingos/parse-irc
  repository: https://github.com/bingos/parse-irc.git
version: 1.20
