---
abstract: 'A parser for the IRC protocol.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-IRC
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
provides:
  Parse::IRC:
    file: lib/Parse/IRC.pm
    version: 1.18
requires:
  perl: 5.6.0
resources:
  homepage: https://github.com/bingos/parse-irc/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/bingos/parse-irc.git
    web: https://github.com/bingos/parse-irc/tree
version: 1.18
