--- 
abstract: A parser for the IRC protocol.
author: Chris Williams
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Parse-IRC
no_index: 
  directory: 
    - inc
    - t
requires: 
  Exporter: 0
version: 1.06
